[project]
name = "calendar-solver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "more-itertools>=10.6.0",
    "numba>=0.60.0",
    "numpy>=2.0.2",
]
